config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "opinions#index"
  resources :users
  resources :opinions do 
    resources :votes, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :comments, only: [:create]
  resources :followings, only: [:create, :destroy]
end

app/views/shared/_follower.html.erb
<div class="follower-item-container">
    <div class="follower-details-wrapper">
        <%= link_to user_path(follower) do%>
        <div class="user-image-follower">
            <div class="image-follower">
                <%= image_tag(follower.photo, class:"img")%>
            </div>
        </div>
        <%end%>
        <div class="follower-details">
            <%= link_to user_path(follower) do%>
            <h3 class="name"><%= follower.full_name.capitalize %></h3>
            <%end%>
            <span class="joined">Joined at <%= follower.created_at.strftime("%Y/%m/%d")%></span>
        </div>
    </div>
    <div class="following-btns-wrapper">
        <%= render_following_btn(follower) %>
    </div>
</div>

app/views/shared/_header.html.erb
<header>
    <%= link_to root_path do%>
    <div class="application-header-logo">
        <%= image_tag('logo.svg')%>
    </div>
    <h3 class="title">Book Reviewer</h3>
    <%end%>
    <nav>
        <ul>
        </ul>
    </nav>
</header>

app/views/shared/_sidebar.html.erb
<div class="side-bar-main-container" data-controller="sidebar">
    <div class="sidebar-header">
        <%= link_to user_path(current_user) do %>
        <div class="user-details">
            <div class="user-image">
                <div class="image">
                    <%= image_tag(current_user.photo)%>
                </div>
            </div>
            <div class="names"><%= current_user.full_name.truncate(15) %></div>
        </div>
        <%end%>
        <div class="following-details">
            <div class="following">
                <h3><%= current_user.following_users.count%></h3>
                <span>Following</span>
            </div>
            <div class="following followers">
                <h3><%= current_user.followers.count%></h3>
                <span>Followers</span>
            </div>
        </div>
    </div>

    <ul>
        <li>
            <%= link_to root_path do%>
            <div class="link-item active" data-sidebar-target="home">
                <div class="icon-wrapper">
                    <i class="bi bi-house-fill"></i>
                </div>
                <div class="link_name">Home</div>
            </div>
            <%end%>
        </li>
        <li>
            <%= link_to user_path(current_user) do%>
            <div class="link-item" data-sidebar-target="profile">
                <div class="icon-wrapper">
                    <i class="bi bi-person-fill"></i>
                </div>
                <div class="link_name">Profile</div>
            </div>

            <%end%>
        </li>
        <li>
            <%= link_to session_path(current_user), method: :delete do%>
            <div class="link-item">
                <div class="icon-wrapper">
                    <i class="bi bi-door-closed-fill"></i>
                </div>
                <div class="link_name">Sign out</div>
            </div>

            <%end%>
        </li>
    </ul>
</div>